### ISSUE TITLE
NTQQ获取Windows密钥失败求助

### ISSUE THREAD

**Issue by StarryForever7** [Brianwind/QQ_msg_analyzer#1]
虽然不应该提在这里，但还是想请教一下
我在参考Windows下获得Key时，QQ版本一致，利用IDA得到的a3地址如下，其中内容包含了很多不可打印字符，要怎么将a3内容转换成明文呢

![debug](https://github.com/Brianwind/QQ_msg_analyzer/assets/51279859/85318581-0740-48d7-aa17-d4b0734018f7)
![hexraw](https://github.com/Brianwind/QQ_msg_analyzer/assets/51279859/575157e9-a220-4c0f-8db4-803e5066abd0)
![sqlcipher](https://github.com/Brianwind/QQ_msg_analyzer/assets/51279859/a392b77b-ff21-475a-91d5-0ff670417762)

**Comment by Brianwind** [comment]
密钥一定是明文，你先去确认一下你打断点的函数有没有问题
以及确认一下是不是先启动qq但不登陆，然后用IDA attach，然后命中断点
不行的话再看看后续有没有其他命中断点的时候
